name: Tebex
version: '${version}'
main: io.tebex.plugin.TebexBukkitPlugin
api-version: 1.13
softdepend:
  - BuycraftX
commands:
  tebex:
    description: The main command
    aliases:
      - buycraft
permissions:
  tebex.buy:
    description: Allows players to open the Tebex buy GUI.
    default: true
