group = rootProject.group
version = rootProject.version

dependencies {
    implementation project(':minecraft-common')

    compileOnly 'net.md-5:bungeecord-api:1.18-R0.1-SNAPSHOT'
    compileOnly 'dev.dejvokep:boosted-yaml:1.3'
}

shadowJar {
    configurations = [project.configurations.runtimeClasspath]

}
