license="MIT"

[[mods]]
modId="tebex"
version="${version}"
displayName="Tebex"
description='''
The Tebex adapter.
'''

[[dependencies.tebex]]
modId="neoforge"
type="required"
versionRange="[26.2.0.57,)"
ordering="NONE"
side="BOTH"

[[dependencies.tebex]]
modId="minecraft"
type="required"
versionRange="[26.2,26.3)"
ordering="NONE"
side="BOTH"
