minecraft_version=26.1
minecraft_version_range=[26.1,26.2)
forge_version=62.0.9
forge_version_range=[62,)
loader_version_range=[62,)

mod_id=tebex
mod_name=Tebex
mod_license=MIT
mod_version=@VERSION@
mod_group_id=io.tebex.plugin
mod_authors=Tebex
mod_description=The official Tebex adapter for Minecraft Forge.
